site_name: Etheirys
site_author: Hao Tran
site_description: >-
  A personal reference guide for FFXIV. 

repo_url: https://github.com/haothitran/etheirys
repo_name: haothitran/etheirys

theme:
  name: material
  language: en
  favicon: assets/favicon.ico

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.expand
    - toc.integrate # integrate table of contents to left sidebar
    - navigation.top 

copyright: All artwork, text, and other assets for FINAL FANTASY XIV © 2010-2022 SQUARE ENIX CO., LTD.
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haothitran/ffxiv-guide

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - admonition # types: note, abstract, info, tip, success, question, warning, failure, danger, bug, example, quote
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: ⚓︎ # add anchor links to headers
      toc_depth: 2 # limit table of contents depth
  # - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list

nav: 
  - Home: index.md
  - General: 
    - general/index.md
    - Jobs: general/jobs.md
    - Glossary: general/glossary.md
  - Duties:
    - duties/duty-finder.md
    - Dungeons: duties/dungeons/index.md
    - Trials: duties/trials/index.md
    - Raids: duties/raids/index.md
  - Relics:
    - relics/index.md
    - Zodiac Weapons: relics/zodiac-weapons.md
    - Anima Weapons: relics/anima-weapons.md
